export default function Hero() {
    return (
        <>  
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        <h1>HEllo</h1>
        </>
)}
